### PR TITLE
Update to rustc 1.4.0-nightly (5aca49c69 2015-08-10)

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by jdm** [comment]
Is it bad that every build failed with other errors?

**Comment by Manishearth** [comment]
I ... guess syntex needs an update too? I'm not sure how this works...

**Comment by oli-obk** [comment]
for nightly without syntex you forgot to update some tests: https://github.com/erickt/rust-aster/blob/master/tests/test_item.rs#L367-L377

**Comment by Manishearth** [comment]
@erickt this still fails travis, I didn't get time to fix it

**Comment by erickt** [comment]
@Manishearth yeah I'm still investigating, I just merged it to save me from writing it :)

**Comment by Manishearth** [comment]
lol.

/me weeps at the thought of a broken master branch

**Comment by erickt** [comment]
we're back to green!

**Pull request merged**
