### PR TITLE
Upgrade to rustc 1.5.0-nightly (98df45830 2015-10-03)

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a4f5f90fba80be6b4213dfbca0c77a0c29321a84
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/serde-rs/aster

---
This message was auto-generated by https://gitcop.com

**Comment by SimonSapin** [comment]
Uh, ok, I suppose the relevant "type" here is "fix", but what does "scope" mean in this context?

**Comment by SimonSapin** [comment]
Anyway, since this branch is in the main repo, feel free to amend it in any way before merging.

**Comment by oli-obk** [comment]
I don't know much about how aster works, but master compiles on stable and beta while your PR doesn't.

**Comment by erickt** [comment]
I merged it in to simplify updates. It also requires an update to [syntex](https://github.com/serde-rs/syntex), which I should have finished shortly. Thanks!

**Pull request merged**
