### PR TITLE
fixed rename DummyMacroLoader -> DummyResolver

### PR DESCRIPTION
**Pull request by jchlapinski**
This fixes broken compilation on latest nightly #105

### CODE REVIEW

**Comment by jchlapinski** [comment]
As a follow up I have made PR for syntex to rename the types as well there https://github.com/serde-rs/syntex/pull/93

**Comment by CooCooCaCha** [comment]
Nice! Is this ready to merge and release?

**Comment by jchlapinski** [comment]
@CooCooCaCha no, not really. The fix is there, but syntex code need to be fixed as well. Currently as You can see I had to temporarily switch syntex repo onto my fork to make tests work. My PR for syntex (https://github.com/serde-rs/syntex/pull/93) was already merged but there is no new release yet so I cannot switch back to original syntex repo. 
Once the fix for syntex is released I will prepare this for merging.

**Comment by oli-obk** [comment]
thanks! I used your commit in #108 and published 0.27

**Pull request closed without merging**
