### PR TITLE
rustup

### PR DESCRIPTION
**Pull request by oli-obk**
breakage due to https://github.com/rust-lang/rust/pull/31487

### CODE REVIEW

**Comment by erickt** [comment]
HA! I just started working on this. Thanks for doing this.

**Comment by oli-obk** [comment]
xD messaged you on irc... Next time i'll post an issue

**Comment by erickt** [comment]
Shucks! I must have missed it then.

**Comment by oli-obk** [comment]
hmm... the build is failing... are there cargo features in aster?

**Comment by erickt** [comment]
@oli-obk: That's because syntex hasn't been updated yet. I'm working on it.

**Comment by tikue** [comment]
I just was about to submit this patch as well. Should have checked open PRs. :P Any updates?

**Pull request merged**
