### PR TITLE
Fixes for issue #76

### PR DESCRIPTION
**Pull request by fabricedesre**
Fixes https://github.com/serde-rs/aster/issues/76

### CODE REVIEW

**Comment by fabricedesre** [comment]
Tests are passing locally. 
r? @erickt

**Comment by fabricedesre** [comment]
Oh, I guess we need to bump the version number...

**Comment by fabricedesre** [comment]
ouch... wtf

**Comment by fabricedesre** [comment]
Ok, I can reproduce when running |cargo build --features with-syntex|

**Comment by KodrAus** [comment]
I think `syntex` will need to be updated too with the changes made to `libsyntax`, right?

**Comment by fabricedesre** [comment]
> I think `syntex` will need to be updated too with the changes made to libsyntax, right?

Yes, I started doing that in https://github.com/serde-rs/syntex/pull/43
No idea so far why println!() ends up being broken...

**Comment by KodrAus** [comment]
@fabricedesre Any update on this? Is there anything else we need to do?

**Comment by fabricedesre** [comment]
@KodrAus I haven't fixed the test failure yet. Any help appreciated!

**Comment by KodrAus** [comment]
Hmm, that `println!` error is really weird... Almost like it's not linking `std`? What's the point of that `hello_world` program?

**Comment by erickt** [comment]
Thanks! I'll fix up the issues on my side.

**Comment by fabricedesre** [comment]
\o/ Thanks @erickt !

**Pull request merged**
